# Generated by Django 5.1.4 on 2025-03-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeeceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids'), ('HOODJACK', 'Hoodjack'), ('ACCESSORIES', 'Accessories')], max_length=250)),
                ('small_descp', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('og_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='core/')),
            ],
        ),
    ]
