# Generated by Django 5.1.4 on 2025-03-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sliderproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderProduct',
        ),
    ]
