# Generated by Django 5.1.4 on 2025-03-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_sliderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images2/')),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
