# Generated by Django 5.1.4 on 2025-03-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeeceCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids'), ('HOODJACK', 'Hoodjack'), ('FOOTWEAR', 'Footwear')], max_length=250)),
                ('small_descp', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('colors', models.CharField(max_length=50)),
                ('sizes', models.CharField(max_length=50)),
                ('og_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='core_dc_2/')),
            ],
        ),
    ]
