# Generated by Django 5.1.4 on 2025-03-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
