# Generated by Django 5.1.4 on 2025-03-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deececategory2',
            old_name='colors',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='deececategory2',
            old_name='og_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='deececategory2',
            old_name='sizes',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='deececategory2',
            name='desc',
        ),
        migrations.AddField(
            model_name='deececategory2',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
