# Generated by Django 5.1.4 on 2025-03-24 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_colors_deececategory2_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product1',
            new_name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='deece_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deececategory2'),
        ),
    ]
