# Generated by Django 5.1.4 on 2025-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
