# Generated by Django 5.1.4 on 2025-03-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
